services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: techpine_laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:randomkey
      - DB_HOST=db
      - DB_PORT=3306 
      - DB_DATABASE=laravel
      - DB_USERNAME=admin
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    image: node:18-alpine
    container_name: techpine_react
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npx next build && npm start"
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: techpine_mysql
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      # - ./init.mysql.sql:/docker-entrypoint-initdb.d/init.mysql.sql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
